### ISSUE TITLE
The articles Build your first Aspire app and Aspire Setup and tooling should have a VS Code tab

### ISSUE THREAD

**Issue by balachir** [dotnet/docs-aspire#850] opened 2024-05-06 11:27 UTC
### Describe the issue or suggestion

For the following documentation, we have 'Visual Studio' and 'CLI' tabs. We should also add a 'VS Code' tab. VS Code C# Dev kit now supports project creation, debug and run of Aspire apps.

- [Build your first .NET Aspire app](https://learn.microsoft.com/en-us/dotnet/aspire/get-started/build-your-first-aspire-app?tabs=visual-studio)
- [Setup and tooling](https://learn.microsoft.com/en-us/dotnet/aspire/fundamentals/setup-tooling?tabs=visual-studio%2Cwindows)

**Comment by balachir** [comment] 2024-05-06 11:28
Including @bradygaster and @kvenkatrajan for awareness

**Comment by IEvangelist** [comment] 2024-05-06 12:17
Related to (perhaps duplicate of) #595

**Comment by balachir** [comment] 2024-05-06 13:35
Note that there's one caveat with project creation using VS Code C# Dev Kit. You can choose the Aspire Starter app template, but you cannot choose the 'Use redis' option during project creation. @kvenkatrajan is this expected behavior for now or should we open a bug? 

![image](https://github.com/dotnet/docs-aspire/assets/8246794/dbe61930-6b4e-4d96-aa02-90bea13cf748)

**Comment by kvenkatrajan** [comment] 2024-05-06 16:20
Yes thats correct.  Currently project options are not available in C# dev kit and the work is in progress. CC: @smitpatel - please confirm if this would be addressed with the options work with the new template engine integration experience. Thanks!

**Comment by smitpatel** [comment] 2024-05-06 17:09
Once all options are added for templates in C# dev kit, Aspire templates would also start showing options to users.

**Closed** 2024-05-21 13:56 UTC
Labels: documentation, :world_map: reQUEST, Pri1, getting-started, doc-enhancement, dotnet-aspire/prod, general-availability
