### ISSUE TITLE
ERROR: only a single Aspire project is supported at this time

### ISSUE THREAD

**Issue by alexhiggins732** [dotnet/docs-aspire#127] opened 2023-12-05 13:39 UTC
### Type of issue

Other (describe below)

### Description

Attempting to follow the documentation after installing the starter kit and running azd init, there is an error that only a single project is supported.

Additionally, the documentation said nothing about needing powershell 7.4 installed but in my case I had to update from 7.2 to 7.4 or the azd command was not found.
![image](https://github.com/dotnet/docs-aspire/assets/2246388/36ed3845-17d9-484e-9068-0e3a646dc2f5)

### Page URL

https://learn.microsoft.com/en-us/dotnet/aspire/deployment/azure/aca-deployment?tabs=visual-studio%2Cinstall-az-windows%2Cpowershell

### Content source URL

https://github.com/dotnet/docs-aspire/blob/main/docs/deployment/azure/aca-deployment.md

### Document Version Independent Id

1362fc62-686d-2b3f-c139-7725fc8dca5f

### Article author

@IEvangelist

---
[Associated WorkItem - 190284](https://dev.azure.com/msft-skilling/Content/_workitems/edit/190284)

**Comment by IEvangelist** [comment] 2023-12-05 17:02
This is by design to my knowledge. A single solution can only have a single AppHost project. Let's double check with @DamianEdwards though before closing this.

**Closed** 2024-01-01 13:09 UTC
Labels: question, needs-more-info, :pushpin: seQUESTered, Pri1
