### ISSUE TITLE
Expand testing docs

### ISSUE THREAD

**Issue by Alirexaa** [dotnet/docs-aspire#1151] opened 2024-06-25 12:03 UTC
### Describe the issue or suggestion

As we add a new `GetEnvironmentVariableValuesAsync` method in https://github.com/dotnet/aspire/pull/4530,

the [testing section](https://learn.microsoft.com/en-us/dotnet/aspire/fundamentals/testing) could be expanded.

I'm not sure it is the only thing we should capture.

**Comment by IEvangelist** [comment] 2024-06-26 14:39
Closing as a duplicate of #1114

**Closed by IEvangelist** 2024-06-26 14:39 UTC
