### ISSUE TITLE
Components has a new name "Integrations"

### ISSUE THREAD

**Issue by sunnynagavo** [dotnet/docs-aspire#1583] opened 2024-08-30 17:23 UTC
### Describe the issue or suggestion

https://devblogs.microsoft.com/dotnet/announcing-dotnet-aspire-8-2/#respond

As pet the new 8.2 release, components are now called as Integrations, should we change and remove all references to components ?

**Comment by IEvangelist** [comment] 2024-09-03 12:03
Closing as duplicate of #1481, which is already done.

**Closed by IEvangelist** 2024-09-03 12:03 UTC
Labels: :watch: Not Triaged
