### ISSUE TITLE
Combining CLI commands in a box makes copying hard

### ISSUE THREAD

**Issue by KathleenDollard** [dotnet/docs-aspire#410] opened 2024-02-22 14:38 UTC
### Description

This is a general comment on docs, that I noticed in this article.

This code block:

> dotnet workload update
> dotnet workload install aspire

must be copied line by line into my terminal. This requires mouse dexterity.   

If it were in two boxes, I could use the copy button. 

### Page URL

https://learn.microsoft.com/en-us/dotnet/aspire/fundamentals/setup-tooling?tabs=visual-studio#install-net-aspire

### Content source URL

https://github.com/dotnet/docs-aspire/blob/main/docs/fundamentals/setup-tooling.md

### Document Version Independent Id

38acc47a-cbda-21f9-5364-2aa038b569a5

### Article author

@IEvangelist

**Comment by IEvangelist** [comment] 2024-02-22 16:20
Closing as duplicate of #409

**Closed by IEvangelist** 2024-02-22 16:20 UTC
