### ISSUE TITLE
[WebToolsE2E][Aspire][Document]Some more updates are needed to "Use .NET Aspire messaging components in ASP.NET Core" instructions using VS with aspire 

### ISSUE THREAD

**Issue by v-yuwzh** [dotnet/docs-aspire#718] opened 2024-04-24 05:29 UTC
### Describe the issue or suggestion

Issue description
In "Use .NET Aspire messaging components in ASP.NET Core" doc, we need to make some updates to the instructions for Preview 6.

**Issue 1**: For [Add the .NET Aspire component to the API](https://learn.microsoft.com/en-us/dotnet/aspire/messaging/messaging-components?tabs=passwordless%2Cvisual-studio#add-the-net-aspire-component-to-the-api) section, document lets add below code,
![image](https://github.com/dotnet/docs-aspire/assets/41678874/acf2e645-1e33-4312-8b2a-a5e8ea82ce30)
after add this code "builder.AddAzureServiceBus("serviceBusConnection");"  will meet below error. change to this code "builder.AddAzureServiceBusClient("serviceBusConnection");" will resolve this issue, so need update the document.
![image](https://github.com/dotnet/docs-aspire/assets/41678874/c698bcb6-19fb-45f4-aed3-ebbd3dab33cc)

**Issue 2**; For [Add the .NET Aspire component to the API](https://learn.microsoft.com/en-us/dotnet/aspire/messaging/messaging-components?tabs=passwordless%2Cvisual-studio#add-the-net-aspire-component-to-the-api) section, when copy below code to machine ,
![image](https://github.com/dotnet/docs-aspire/assets/41678874/94d2611c-34f4-483e-8c14-20da6812f760)
It will meet below issue as below screenshot, so need update the document. 
![image](https://github.com/dotnet/docs-aspire/assets/41678874/1fca75cb-4a26-43ff-80fc-b4194ff65541)

**Issue 3** For [Create the API endpoint](https://learn.microsoft.com/en-us/dotnet/aspire/messaging/messaging-components?tabs=connection-string%2Cvisual-studio#create-the-api-endpoint) section, document  lets copy below codes, 
![image](https://github.com/dotnet/docs-aspire/assets/41678874/e03327ff-bec7-4c51-bd16-65cdc8e3cb0c)
After add below code, it will show an error, when add ";" in line 38, this error will disappear, so the document. need update.
![image](https://github.com/dotnet/docs-aspire/assets/41678874/f6b67de5-f020-40c3-bad6-4fb2ee6dce10)

**Comment by IEvangelist** [comment] 2024-06-05 19:05
Closing as duplicate of #489 - and being addressed as part of #1043

**Closed by IEvangelist** 2024-06-05 19:05 UTC
Labels: duplicate
