### ISSUE TITLE
Order of steps is inconsistent across different pages

### ISSUE THREAD

**Issue by matt-goldman** [dotnet/docs-aspire#2098] opened 2024-11-15 23:49 UTC
### Type of issue

Other (describe below)

### Description

Tagged one article here, but just an observation that it would be great if the order of steps in the integrations docs was consistent.

For example, in this doc (on PostgreSQL with EF Core), the steps are:

**1. Add the hosting integration package _to the app host_**
2. Add the server resource
3. Add pgAdmin (side note - it's awesome that you can include this here! 🎉)
4. [...additional configuration options in the app host...]
5. Client integration (https://learn.microsoft.com/dotnet/aspire/database/postgresql-entity-framework-integration?tabs=dotnet-cli#client-integration) ...
**6. Add the Aspire package _to the consumer_**

The interim steps aren't that important, but this seems to me like the right order and a sensible way to do things. Compare this for example to the storage integration steps (https://learn.microsoft.com/dotnet/aspire/storage/azure-storage-blobs-integration?tabs=dotnet-cli)

**1. Add the Aspire package _to the consumer_**
2. Example usage
**3. Add the hosting integration package _to the app host_**

I don't think this order makes as much sense. But either way, I think it would be much easier to follow the docs if the order across these pages was consistent.

### Page URL

https://learn.microsoft.com/en-us/dotnet/aspire/database/postgresql-entity-framework-integration?tabs=dotnet-cli#see-also

### Content source URL

https://github.com/dotnet/docs-aspire/blob/main/docs/database/postgresql-entity-framework-integration.md

### Document Version Independent Id

b0430379-092c-6361-27aa-a4c48d6b641e

### Article author

@CamSoper

**Comment by IEvangelist** [comment] 2024-11-21 02:06
Closing as a duplicate of #1765. I'm currently re-writing all integration articles. Some of the articles that are done follow the desired flow that you mention. Happy that we're already moving in the right direction. Some of the articles that are already done are mentioned in that issue. Go look at their corresponding pages, for example:

- [.NET Aspire Redis integration](https://learn.microsoft.com/en-us/dotnet/aspire/caching/stackexchange-redis-integration)

I'm going to close this one as were already on it. But thank you so much for posting it!

**Closed by IEvangelist** 2024-11-21 02:06 UTC
