### ISSUE TITLE
New Elasticsearch article

### ISSUE THREAD

**Issue by eerhardt** [dotnet/docs-aspire#1379] opened 2024-07-18 14:28 UTC
We added 2 new libraries to Aspire:

* Aspire.Hosting.Elasticsearch
* Aspire.Elastic.Clients.Elasticsearch

See https://github.com/dotnet/aspire/pull/4430 for more details.

We should add an article on Elasticsearch and how to use it in .NET Aspire.

**Comment by IEvangelist** [comment] 2024-07-23 13:26
Duplicate of #1059

**Closed by IEvangelist** 2024-07-23 13:26 UTC
Labels: :watch: Not Triaged
